import type { HudMessages } from './hudText.types';

export const HUD_TEXT_ZH_CN: HudMessages = {
  playerInfo: '玩家信息',
  playerName: '玩家名称',
  playerLevel: '等级 {level}',
  health: '生命值 {value} / {maximum}',
  mana: '法力值 {value} / {maximum}',
  experience: '经验值 {value} / {maximum}',
  experienceValue: '经验 {value} / {maximum}',
  wavePanel: '怪物波次',
  waveTitle: '第 {wave} 波',
  nextWaveCountdown: '下一波倒计时 {time}',
  bossProgress: '已通过 {completed} / {total} 个首领节点',
  pause: '暂停',
  settings: '设置',
  currencyInfo: '货币信息',
  gold: '金币',
  energy: '收集能量',
  gemProgress: '蓝色宝石收集进度',
  activeSkills: '主动技能栏',
  activeSkillSlot: '主动技能 {key}',
  emptyActiveSkillSlot: '主动技能 {key}，空槽位',
  itemQuickbar: '物品快捷栏',
  itemSlot: '物品快捷键 {key}',
  itemEffect: '物品 {key} 效果',
  cooldownPanel: '技能与药效冷却',
  skillSweep: '横扫',
  skillSpin: '回旋',
  skillWave: '破空',
  skillHeavenSplit: '开天',
  skillSkyArrow: '穿云箭',
};
