import type { HudMessages } from './hudText.types';

export const HUD_TEXT_ZH_CN: HudMessages = {
  gameTitle: '铁壁',
  playerLevel: '等级 {level}',
  health: '生命值 {value} / {maximum}',
  mana: '法力值 {value} / {maximum}',
  experience: '经验值 {value} / {maximum}',
  experienceValue: '经验 {value} / {maximum}',
  wavePanel: '怪物波次',
  waveTitle: '第 {wave} 波',
  finalStandTitle: '倒 计 时',
  nextWaveCountdown: '下一波倒计时 {time}',
  waveProgress: '已打完 {completed} / {total} 波',
  pauseHint: '按 ESC 暂停',
  language: '语言',
  sound: '音效',
  music: '音乐',
  on: '开',
  off: '关',
  currencyInfo: '货币信息',
  gold: '金币',
  energy: '灵石',
  gemProgress: '蓝色宝石收集进度',
  activeSkills: '主动技能栏',
  activeSkillSlot: '主动技能 {key}',
  emptyActiveSkillSlot: '主动技能 {key}，空槽位',
  itemQuickbar: '物品快捷栏',
  itemSlot: '物品快捷键 {key}',
  itemEffect: '物品 {key} 效果',
  cooldownPanel: '技能与药效冷却',
  skillSweep: '横扫',
  skillSpin: '回旋',
  skillWave: '破空',
  skillHeavenSplit: '开天',
  skillSkyArrow: '穿云箭',
  skillLunge: '突进',
  skillAegis: '金钟罩',
  skillDharma: '天地法相',
  skillSprint: '疾走',
  skillIronBody: '铁布衫',
  skillBulwark: '磐石',
  skillMend: '回春',
  skillBerserk: '狂暴',
  skillBloodthirst: '饮血',
};
