import type { HudMessages } from './hudText.types';

export const HUD_TEXT_EN: HudMessages = {
  gameTitle: 'IronWall',
  playerLevel: 'Lv. {level}',
  health: 'HEALTH {value} / {maximum}',
  mana: 'MANA {value} / {maximum}',
  experience: 'EXPERIENCE {value} / {maximum}',
  experienceValue: 'XP {value} / {maximum}',
  wavePanel: 'MONSTER WAVE',
  waveTitle: 'WAVE {wave}',
  finalStandTitle: 'COUNTDOWN',
  nextWaveCountdown: 'NEXT WAVE IN {time}',
  waveProgress: '{completed} / {total} WAVES CLEARED',
  pauseHint: 'PRESS ESC TO PAUSE',
  language: 'LANGUAGE',
  currencyInfo: 'CURRENCY',
  gold: 'GOLD',
  energy: 'SPIRIT STONES',
  gemProgress: 'BLUE GEM COLLECTION PROGRESS',
  activeSkills: 'ACTIVE SKILLS',
  activeSkillSlot: 'ACTIVE SKILL {key}',
  emptyActiveSkillSlot: 'ACTIVE SKILL {key}, EMPTY SLOT',
  itemQuickbar: 'ITEM QUICKBAR',
  itemSlot: 'ITEM SHORTCUT {key}',
  itemEffect: 'ITEM {key} EFFECT',
  cooldownPanel: 'SKILL AND EFFECT COOLDOWNS',
  skillSweep: 'SWEEP',
  skillSpin: 'SPIN',
  skillWave: 'WAVE',
  skillHeavenSplit: 'HEAVEN SPLIT',
  skillSkyArrow: 'SKY ARROW',
  skillLunge: 'LUNGE',
  skillAegis: 'GOLDEN BELL',
  skillDharma: 'DHARMA FORM',
  skillSprint: 'SPRINT',
  skillIronBody: 'IRON BODY',
  skillBulwark: 'BULWARK',
  skillMend: 'MEND',
  skillBerserk: 'BERSERK',
  skillBloodthirst: 'BLOODTHIRST',
};
